package com.diemlife.models;

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.apache.catalina.Role;
import org.apache.catalina.UserDatabase;

import com.fasterxml.jackson.annotation.JsonBackReference;

/**
 * SecurityRole generated by hbm2java
 */
@Entity
@Table(name = "security_role")
public class SecurityRole implements java.io.Serializable, Role {

    /**
     *
     */
    private static final long serialVersionUID = 1L;
    private Integer id;
    private String roleName;
    private Set<User> users = new HashSet<User>(0);

    public SecurityRole() {
    }

    public SecurityRole(String roleName, Set<User> users) {
        this.roleName = roleName;
        this.users = users;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "role_name")
    public String getRoleName() {
        return this.roleName;
    }

    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    @ManyToMany(fetch = FetchType.LAZY)
    @JoinTable(name = "user_has_security_role", joinColumns = { @JoinColumn(name = "security_role_id", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "user_id", nullable = false, updatable = false) })
    @JsonBackReference
    public Set<User> getUsers() {
        return this.users;
    }

    public void setUsers(Set<User> users) {
        this.users = users;
    }

    @Override
    @Transient
    public String getName() {
        // TODO Auto-generated method stub
        return this.getRoleName();
    }

	@Override
	public String getDescription() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public String getRolename() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public UserDatabase getUserDatabase() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public void setDescription(String arg0) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void setRolename(String arg0) {
		// TODO Auto-generated method stub
		
	}

}